### ISSUE TITLE
Auth before SMTP

### ISSUE THREAD

**Issue by jkatiku** [Exim4U/src#1]
I would like to do Auth Before SMTP using SASLAUTHD.

How do i go about it..
i have not seen provision for this in the source code.

Katiku J.

**Comment by gldickens3** [comment]
```
You will need to modify
  /etc/exim/exim.conf as described in the exim wiki here:

  https://github.com/Exim/exim/wiki/AuthenticatedSmtpUsingSaslauthd

  I hope that this helps.  Good luck.

  Gordon



  On 02/23/2016 03:14 AM, jkatiku wrote:


  I would like to do Auth Before SMTP using SASLAUTHD.
  How do i go about it..
    i have not seen provision for this in the source code.
  Katiku J.
  —
    Reply to this email directly or view it on
      GitHub.
```

**Comment by jkatiku** [comment]
I got the link and it was helpful. however i am struggling to rewrite the items below to allow mysql Query. it does not seem to be working. please advise.

# For encrypted passwords, use the following two authenticators:

plain_login_exim4u:
        driver = plaintext
        public_name = PLAIN
        server_condition = ${if saslauthd{crypteq{$auth3}{${lookup mysql{ \
                                SELECT crypt FROM users \
                                WHERE username='${quote_mysql:$auth2}' \
                                }}}{1}{0}}}
        server_set_id = $auth2
        server_advertise_condition = true

fixed_login_exim4u:
        driver = plaintext
        public_name = LOGIN
        server_prompts = "Username:: : Password::"

```
    server_condition = ${if saslauthd{crypteq{$auth2}{${lookup mysql{ \
                            SELECT crypt FROM users \
                            WHERE username='${quote_mysql:$auth1}' \
                            }}}{1}{0}}}
    server_set_id = $auth1
    server_advertise_condition = true
```

Can you assist please..

Katiku J.

**Comment by gldickens3** [comment]
I hope that you were able to resolve this problem, however, AUTH before smtp is not a feature of Exim4U. Therefore, I am going to close this issue.
